### ISSUE TITLE
Construction of LngString apparently did not work

### ISSUE THREAD

**Issue by giacomomarchioro** [iiif-prezi/iiif-prezi3#11] opened 2021-10-09 11:48 UTC
https://github.com/iiif-prezi/iiif-prezi3/blob/2f38fc6c439264de8caa552f40c455596a97d8cd/iiif_prezi3/skeleton.py#L62-L63

Seems that the construction of the LngString class did not produce the expected output. 

```
from iiif_prezi3 import Manifest
man = Manifest(id="https://test.com",type="Manifest",label={"en": [ "A test" ]})
man.json(exclude_unset=True)
```

**Comment by glenrobson** [comment] 2022-02-11 13:24
I should have used this ticket but didn't see it so this is now a duplicate of: https://github.com/iiif-prezi/iiif-prezi3/issues/23

**Closed by glenrobson** 2022-02-11 13:24 UTC
