### ISSUE TITLE
mkdocs is not currently buillding documentation from the docstrings

### ISSUE THREAD

**Issue by digitaldogsbody** [iiif-prezi/iiif-prezi3#130] opened 2022-12-02 15:54 UTC
The mkdocstrings plugin is included in https://github.com/iiif-prezi/iiif-prezi3/blob/main/mkdocs.yml and there is what I assume to be a file that should trigger it for the library in https://github.com/iiif-prezi/iiif-prezi3/blob/main/docs/code.md but the generated docs are blank for that section: https://iiif-prezi.github.io/iiif-prezi3/code/

**Comment by helrond** [comment] 2022-12-03 00:54
I looked into this briefly, and it appears that `mkdocstrings` is expecting you to point to a module (i.e. `::: iiif_prezi3.helpers.add_item`, not `::: iiif_prezi3`. So, we _could_ add references for all those modules to  https://github.com/iiif-prezi/iiif-prezi3/blob/main/docs/code.md BUT that seems like a maintenance nightmare because we'd have to update that page whenever a new helper is added. There look to be some solutions for this like https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages but I haven't had the chance yet to dig in there.

**Comment by digitaldogsbody** [comment] 2022-12-03 02:23
Thanks Hillel. The extra modules linked on that page look promising, and if worst comes to worst, we could probably autogenerate the skeleton .md files using a script in the docs workflow

**Comment by digitaldogsbody** [comment] 2022-12-06 12:03
After merging @rlskoeser's fix - I am still not seeing the docstrings. However, there looks like there is something odd going on with the workflow: https://github.com/iiif-prezi/iiif-prezi3/actions/runs/3629265185/jobs/6121308959

The mkdocs step says
> Building documentation to directory: /home/runner/work/iiif-prezi3/iiif-prezi3/site

but then the "upload to giuthub pages" action gets:
>   [INFO] copy /home/runner/work/iiif-prezi3/iiif-prezi3/site to /home/runner/actions_github_pages_1670327949848
  cp: no such file or directory: /home/runner/work/iiif-prezi3/iiif-prezi3/site/.*

**Comment by digitaldogsbody** [comment] 2022-12-06 13:13
If I changecode.md to be e.g `::: iiif_prezi3.helpers.AddItem` then I get the generation for that helper class ok

**Comment by rlskoeser** [comment] 2022-12-06 14:30
drat, I forgot to check versions — when I tested locally I was apparently using an older version that what is specified in `setup.py` and what's being used in the github actions workflow. I don't know why that would matter, maybe there's a regression somewhere in mkdocstrings or one of the dependencies.

fwiw, while I was looking I saw that there is a `mkdocs gh-deploy` command; wonder if that would be any simpler than using the github pages action.

**Comment by glenrobson** [comment] 2022-12-09 14:19
Hillel to have a look the code option in: https://github.com/iiif-prezi/iiif-prezi3/issues/130#issuecomment-1335992990 but @rlskoeser if you've got time we could do with your help :-)

**Comment by rlskoeser** [comment] 2022-12-09 15:01
FWIW, just tested locally with versions. When I install an older version with `pip install "mkdocstrings-python<0.7"` then the build generates output for the code page (and I get lots of warnings and errors). When I install any version newer than that, no warnings and no output in the built file. Not sure why this is, but a shorter term fix might be to use the older version — maybe there's a problem with mkdocstrings-python that will resolved in a future release.

**Comment by digitaldogsbody** [comment] 2022-12-09 15:09
> [mkdocstrings/python#36](https://github.com/mkdocstrings/python/issues/36)
> 
> This might be the answer!

Yes! PR incoming...

**Closed** 2022-12-09 15:30 UTC
Labels: bug, documentation, infrastructure
